#!/usr/bin/perl -w
# 
# Copyright (c) 2012 Nedokushev Michael <grouzen.hexy@gmail.com>
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# About program:
#    taskwatcher is an small piece of perl code
#    to note time that you spend working on tasks.
# 

use strict;
use utf8;

use File::Lockfile;

use Pod::Usage;
use Getopt::Long;

use Local::Taskwatcher::DB;
use Local::Taskwatcher::Printer qw(INFO SUCCESS ERROR);

# Format of the db file:
# current: taskname
# tasks:
#     task1:
#         descr: very cool description of this task
#         time: 01201230123
#         create_time: 123123123123
#         done: 0
#         days:
#             2012_11_28: 012301230
#             2012_11_27: 0123232323
#         commits:
#             hashkeyofcommit:
#                create_time: 123123123
#                spended_time: 12312
#         tasks:
#              -/same info as on parent task/-
#      task2:
#         ...
#
my $dbfilename = $ENV{HOME} . "/.taskwatcher.db";

# Lockfile need to prevent of starting several taskwatchers apps
my $lockfile = File::Lockfile->new("taskwatcher.pid", '/tmp');

my $options = {
    descrption => '',
    verbose => 0
};

# Launch program.
GetOptions("help|usage" => sub { pod2usage(-verbose => 2, -exitval => 0) },
           "verbose" => \$options->{verbose},
           "add|create=s" => \$options->{add},
           "remove|delete=s" => \$options->{remove},
           "edit=s" => \$options->{edit},
           "description=s" => \$options->{description},
           "run=s" => \$options->{run},
           "stop=s" => \$options->{stop},
           "status=s" => \$options->{status},
           "tasks-list" => \$options->{tasks_list}
    );

my $printer = Local::Taskwatcher::Printer->new($options->{verbose});
my $db = Local::Taskwatcher::DB->new($dbfilename, $printer);
return if !defined($db->open());

if($options->{status}) {
    $db->status($options->{status});
    exit 0;
} elsif($options->{tasks_list}) {
    $db->tasks_list();
    exit 0;
}

if(my $pid = $lockfile->check()) {
    print $printer->p("taskwatcher is already running with PID: $pid\n");
    exit;
}

$lockfile->write;

if($options->{add}) {
    $db->add_task($options->{add}, $options->{description});
} elsif($options->{remove}) {
    $db->remove_task($options->{remove});
} elsif($options->{run}) {
    my $task = $db->get_task($options->{run});

    if(defined($task)) {
        my $ticks = 0;

        while(1) {
            print "\r" . $printer->p($printer->human_time($task->delta_time + $ticks));

            sleep(1);
            $ticks++;

            if($db->need_update($ticks)) {
                $task->add_delta_time($ticks);
                $db->write();
                $ticks = 0;
            }
        }
    } else {
        print "Task not found: $options->{run}\n";
    }
}

$lockfile->remove;

__END__

=head1 NAME

TaskWatcher

=head1 SYNOPSIS

taskwatcher [options]

Options:
    -h, --help, --usage                     Show this message.
    -a, --add, --create=taskname            Create task with a taskname.
    -r, --remove, --delete=taskname         Remove task with a taskname.
    -e, --edit=taskname                     Edit a taskname.
    -d, --description=description           Set a description of task.
    -r, --run=taskname                      Run existing taskname.
    -s, --stop=taskname                     Stop existing taskname.
    -v, --verbose                           Write more.
    
=cut
